language: python
cache: pip
services:
  - mongodb
python: 3.6
before_install:
  - cp .env.ci .env
  - mkdir -p build
  - mkdir -p build/static
  - cp static/main.css build/static/main.css
install:
  - pip install -r requirements.txt
script:
  - python scrap.py
  - python web.py dump
after_success:
   - "if [ \"$TRAVIS_BRANCH\" == \"master\" ]; then curl -T build/index.html -u $FTP_USER:$FTP_PASSWORD ftp://$FTP_HOST/index.html; fi"
   - "if [ \"$TRAVIS_BRANCH\" == \"master\" ]; then curl -T build/index.html -u $FTP_USER:$FTP_PASSWORD ftp://$FTP_HOST/$(date +%Y-%m-%d).html; fi"
   - "if [ \"$TRAVIS_BRANCH\" == \"master\" ]; then curl -T build/last.json -u $FTP_USER:$FTP_PASSWORD ftp://$FTP_HOST/last.json; fi"
   - "if [ \"$TRAVIS_BRANCH\" == \"master\" ]; then curl -T build/last.json -u $FTP_USER:$FTP_PASSWORD ftp://$FTP_HOST/$(date +%Y-%m-%d).json; fi"
   - "if [ \"$TRAVIS_BRANCH\" == \"master\" ]; then curl -T static/main.css -u $FTP_USER:$FTP_PASSWORD ftp://$FTP_HOST/static/main.css; fi"
notifications:
  email:
    recipients:
      - oziveni@oziveni.cz
    on_success: never # default: change
    on_failure: always # default: always
