language: python
cache: pip
services:
  - mongodb
python: 3.6
before_install:
  - cp .env.ci .env
  - mkdir -p build
  - mkdir -p build/static
  - cp static/main.css build/static/main.css
install:
  - pip install -r requirements.txt
script:
  - python scrap.py
  - python web.py dump
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: build
  on:
    branch: travis
